cd "C:\Moebius"
moebius /log /bat /to 0 /ln "RLibPlus" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\RLibPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_Button" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibButtonPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_Calendar" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibCalendarPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_ComboBox" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibComboBoxPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_Editor" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibEditorPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_IPAddress" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibIPAddressPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_ListIcon" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibListIconPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_ListView" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibListViewPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_Panel" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibPanelPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_ProgressBar" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibProgressBarPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_ScrollBar" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibScrollbarPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_StatusBar" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibStatusBarPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_String" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibStringPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_Toolbar" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibToolbarPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_ToolTip" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibToolTipPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_Trackbar" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibTrackbarPlus.pb"
moebius /log /bat /to 0 /ln "RLibPlus_Tree" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\IncLib\LibTreePlus.pb"
moebius /log /bat /to 1 /ln "RLibPlus.res" /pbi "Prefs/Profile_Windows.ini" "K:\RLibPlus\RLibPlus_Res.pb"
pause