#TVM_SETTOOLTIPS          = #TV_FIRST + 24
#TVM_GETTOOLTIPS          = #TV_FIRST + 25
#TVM_SETINSERTMARK        = #TV_FIRST + 26
#TVM_SETITEMHEIGHT        = #TV_FIRST + 27
#TVM_GETITEMHEIGHT        = #TV_FIRST + 28
#TVM_SETBKCOLOR           = #TV_FIRST + 29
#TVM_SETTEXTCOLOR         = #TV_FIRST + 30
#TVM_GETBKCOLOR           = #TV_FIRST + 31
#TVM_GETTEXTCOLOR         = #TV_FIRST + 32
#TVM_SETSCROLLTIME        = #TV_FIRST + 33
#TVM_GETSCROLLTIME        = #TV_FIRST + 34
#TVM_SETINSERTMARKCOLOR   = #TV_FIRST + 37
#TVM_GETINSERTMARKCOLOR   = #TV_FIRST + 38
#TVM_GETITEMSTATE         = #TV_FIRST + 39
#TVM_SETLINECOLOR         = #TV_FIRST + 40
#TVM_GETLINECOLOR         = #TV_FIRST + 41

#TVM_GETUNICODEFORMAT     = #CCM_GETUNICODEFORMAT
#TVM_SETUNICODEFORMAT     = #CCM_SETUNICODEFORMAT

#TVE_EXPANDPARTIAL        = $4000
#TVE_COLLAPSERESET        = $8000
#TVIF_INTEGRAL            = $80
#TVIS_EXPANDPARTIAL       = $80
#TVSI_NOSINGLEEXPAND      = $8000