#TCM_SETMINTABWIDTH     = #TCM_FIRST + 49
#TCM_DESELECTALL        = #TCM_FIRST + 50
#TCM_HIGHLIGHTITEM      = #TCM_FIRST + 51
#TCM_SETEXTENDEDSTYLE   = #TCM_FIRST + 52
#TCM_GETEXTENDEDSTYLE   = #TCM_FIRST + 53

#TCM_GETUNICODEFORMAT   = #CCM_GETUNICODEFORMAT
#TCM_SETUNICODEFORMAT   = #CCM_SETUNICODEFORMAT

#TCIF_STATE             = $10
#TCS_EX_FLATSEPARATORS  = $1
#TCS_EX_REGISTERDROP    = $2
; IDE Options = PureBasic v4.00 (Windows - x86)
; CursorPosition = 11
; Folding = -
; EnableXP